

trigger:
- main

pool:
  vmImage: ubuntu-latest
 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: kawther23/devops-appv1.0 
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

# Starter pipeline
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Kawther Adam DevOps(069aabee-fed9-4d93-8b03-d24c331f52ad)'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
  

