# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  displayName: 'Build and push image to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kawther23/devops-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v1:0'

